# Generated by Django 4.2.10 on 2024-04-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_answer_type_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_code',
            field=models.CharField(default='E1', max_length=2),
            preserve_default=False,
        ),
    ]
