# Generated by Django 4.2.10 on 2024-05-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_rename_personality_type_major_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_name',
            field=models.CharField(),
        ),
    ]
