# Generated by Django 4.2.10 on 2024-05-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_alter_major_major_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='majors',
            field=models.TextField(default='major'),
            preserve_default=False,
        ),
    ]
